# Generated by Django 4.0.3 on 2022-03-08 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(default=None)),
                ('city', models.CharField(max_length=200)),
                ('post_code', models.IntegerField(default=None)),
                ('street', models.CharField(default=None, max_length=100)),
                ('house_number', models.IntegerField(default=None)),
                ('land_mark', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('image', models.CharField(max_length=100)),
            ],
        ),
    ]
