# Generated by Django 4.0.3 on 2022-03-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.CharField(default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='location',
            name='house_number',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='land_mark',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='post_code',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='location',
            name='street',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
